export { runLfs } from './plugins/run-lfs'
export { commit } from './plugins/commit'
export { publish } from './plugins/publish'
export { testPublish } from './plugins/test-publish'
export { activate } from './plugins/activate'
export { test } from './plugins/test'
